#!/usr/bin/env python3
"""
Script to enhance the telemetry frontend with QR Code Management section.

This script adds a QR Code Management card to the telemetry dashboard frontend.
"""

from pathlib import Path
import re

# QR Code Management HTML section to insert
QR_MANAGEMENT_SECTION = '''
        <!-- QR Code Management Card -->
        <div class="card full-width">
            <div class="card-header">
                <h3 class="card-title"><i class="fas fa-qrcode"></i> QR Code Management</h3>
                <button class="btn btn-primary" onclick="loadQRURLs()">
                    <i class="fas fa-sync-alt"></i> Refresh
                </button>
            </div>

            <!-- Current QR URLs -->
            <div class="control-section">
                <h4>Current QR Code URLs</h4>
                <div class="qr-url-display">
                    <div class="form-group">
                        <label>Base URL:</label>
                        <input type="text" class="input-field" id="qrBaseUrl" readonly>
                        <button class="btn btn-secondary btn-small" onclick="copyToClipboard(document.getElementById('qrBaseUrl').value)">
                            <i class="fas fa-copy"></i>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Update QR URLs -->
            <div class="control-section">
                <h4>Update QR URLs</h4>
                <div class="qr-update-form">
                    <div class="form-group">
                        <label>New Base URL:</label>
                        <input type="text" class="input-field" id="newQrBaseUrl" placeholder="https://example.com/purchase">
                    </div>

                    <div class="form-group">
                        <label>Level-Specific URLs (Optional):</label>
                        <div class="level-url-grid" id="levelUrlsGrid">
                            <!-- Generated by JavaScript -->
                        </div>
                        <button class="btn btn-secondary btn-small" onclick="toggleLevelURLs()">
                            <i class="fas fa-chevron-down"></i> <span id="levelUrlsToggle">Show Level URLs</span>
                        </button>
                    </div>

                    <div class="form-group">
                        <label>PIN:</label>
                        <input type="password" class="input-field" id="qrUpdatePin" placeholder="Enter PIN">
                    </div>

                    <div class="btn-group">
                        <button class="btn btn-primary" onclick="updateQRURLs()">
                            <i class="fas fa-save"></i> Update URLs
                        </button>
                        <button class="btn btn-secondary" onclick="regenerateQRCodes()">
                            <i class="fas fa-sync-alt"></i> Regenerate QR Codes
                        </button>
                    </div>
                </div>
            </div>

            <!-- QR Code Preview -->
            <div class="control-section">
                <h4>Preview QR Codes</h4>
                <div class="qr-preview-grid" id="qrPreviewGrid">
                    <!-- Generated by JavaScript -->
                </div>
            </div>
        </div>

'''

# Additional CSS for QR Management
QR_MANAGEMENT_CSS = '''
        /* QR Code Management Styles */
        .qr-url-display {
            margin-bottom: 1.5rem;
        }

        .qr-update-form {
            background: var(--bg-secondary);
            padding: 1.5rem;
            border-radius: 12px;
        }

        .form-group {
            margin-bottom: 1.5rem;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: 500;
            color: var(--text-primary);
        }

        .input-field {
            width: 100%;
            padding: 0.75rem 1rem;
            background: var(--bg-card);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            color: var(--text-primary);
            font-size: 0.9rem;
            font-family: 'Inter', sans-serif;
        }

        .input-field:focus {
            outline: none;
            border-color: var(--accent-primary);
        }

        .input-field[readonly] {
            background: var(--bg-secondary);
            opacity: 0.7;
        }

        .level-url-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 1rem;
            margin-top: 1rem;
            margin-bottom: 1rem;
            display: none;
        }

        .level-url-grid.show {
            display: grid;
        }

        .level-url-item {
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }

        .level-url-item label {
            min-width: 80px;
            margin-bottom: 0;
        }

        .level-url-item input {
            flex: 1;
        }

        .qr-preview-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 1rem;
        }

        .qr-preview-item {
            background: var(--bg-secondary);
            padding: 1rem;
            border-radius: 12px;
            text-align: center;
        }

        .qr-preview-item h5 {
            margin-bottom: 0.75rem;
            color: var(--accent-primary);
        }

        .qr-preview-canvas {
            background: white;
            padding: 10px;
            border-radius: 8px;
            margin: 0 auto;
        }

        .btn-small {
            padding: 0.5rem 1rem;
            font-size: 0.85rem;
        }

        .full-width {
            grid-column: 1 / -1;
        }
'''

# Additional JavaScript for QR Management
QR_MANAGEMENT_JS = '''
        // QR Code Management Functions
        let currentQRURLs = {
            base_url: '',
            level_urls: {}
        };

        async function loadQRURLs() {
            try {
                const response = await fetch('/api/qr-urls');
                const data = await response.json();

                currentQRURLs = data;
                document.getElementById('qrBaseUrl').value = data.base_url;

                // Update preview
                updateQRPreview();

            } catch (error) {
                showNotification('Failed to load QR URLs: ' + error.message, 'error');
            }
        }

        async function updateQRURLs() {
            const baseUrl = document.getElementById('newQrBaseUrl').value.trim();
            const pin = document.getElementById('qrUpdatePin').value;

            if (!pin) {
                showNotification('Please enter PIN', 'warning');
                return;
            }

            try {
                const response = await fetch('/api/qr-urls', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        pin: pin,
                        base_url: baseUrl || undefined,
                        level_urls: getLevelURLsFromForm()
                    })
                });

                if (response.ok) {
                    const data = await response.json();
                    showNotification('QR URLs updated successfully', 'success');
                    document.getElementById('qrUpdatePin').value = '';
                    document.getElementById('newQrBaseUrl').value = '';
                    await loadQRURLs();
                } else {
                    const error = await response.json();
                    showNotification(error.detail || 'Failed to update QR URLs', 'error');
                }
            } catch (error) {
                showNotification('Failed to update QR URLs: ' + error.message, 'error');
            }
        }

        async function regenerateQRCodes() {
            const pin = document.getElementById('qrUpdatePin').value;

            if (!pin) {
                showNotification('Please enter PIN', 'warning');
                return;
            }

            try {
                const response = await fetch(`/api/qr-urls/regenerate?pin=${encodeURIComponent(pin)}`, {
                    method: 'POST'
                });

                if (response.ok) {
                    showNotification('QR codes regeneration triggered', 'success');
                    document.getElementById('qrUpdatePin').value = '';
                } else {
                    const error = await response.json();
                    showNotification(error.detail || 'Failed to regenerate QR codes', 'error');
                }
            } catch (error) {
                showNotification('Failed to regenerate QR codes: ' + error.message, 'error');
            }
        }

        function toggleLevelURLs() {
            const grid = document.getElementById('levelUrlsGrid');
            const toggle = document.getElementById('levelUrlsToggle');

            if (grid.classList.contains('show')) {
                grid.classList.remove('show');
                toggle.textContent = 'Show Level URLs';
            } else {
                grid.classList.add('show');
                toggle.textContent = 'Hide Level URLs';

                // Generate level URL inputs if not already done
                if (grid.children.length === 0) {
                    for (let i = 1; i <= 10; i++) {
                        const div = document.createElement('div');
                        div.className = 'level-url-item';
                        div.innerHTML = `
                            <label>Level ${i}:</label>
                            <input type="text" class="input-field" id="levelUrl${i}"
                                   placeholder="Leave empty to use base URL">
                        `;
                        grid.appendChild(div);
                    }
                }
            }
        }

        function getLevelURLsFromForm() {
            const levelUrls = {};
            for (let i = 1; i <= 10; i++) {
                const input = document.getElementById(`levelUrl${i}`);
                if (input && input.value.trim()) {
                    levelUrls[i] = input.value.trim();
                }
            }
            return Object.keys(levelUrls).length > 0 ? levelUrls : undefined;
        }

        function updateQRPreview() {
            const grid = document.getElementById('qrPreviewGrid');
            grid.innerHTML = '';

            // For now, show text preview. QR code generation would require a library
            for (let i = 1; i <= 10; i++) {
                const url = currentQRURLs.level_urls[i] ||
                           `${currentQRURLs.base_url}?level=${i}&machine=${machineId}`;

                const div = document.createElement('div');
                div.className = 'qr-preview-item';
                div.innerHTML = `
                    <h5>Level ${i}</h5>
                    <div class="qr-preview-text" style="font-size: 0.75rem; color: var(--text-secondary); word-break: break-all;">
                        ${url}
                    </div>
                `;
                grid.appendChild(div);
            }
        }

        function copyToClipboard(text) {
            navigator.clipboard.writeText(text).then(() => {
                showNotification('Copied to clipboard', 'success');
            }).catch(() => {
                showNotification('Failed to copy', 'error');
            });
        }

        function showNotification(message, type = 'info') {
            // Create notification element
            const notification = document.createElement('div');
            notification.className = `notification notification-${type}`;
            notification.textContent = message;
            notification.style.cssText = `
                position: fixed;
                top: 20px;
                right: 20px;
                padding: 1rem 1.5rem;
                background: ${type === 'success' ? 'var(--accent-success)' : type === 'error' ? 'var(--accent-danger)' : 'var(--accent-warning)'};
                color: white;
                border-radius: 8px;
                box-shadow: 0 4px 12px rgba(0,0,0,0.3);
                z-index: 10000;
                animation: slideIn 0.3s ease;
            `;

            document.body.appendChild(notification);

            setTimeout(() => {
                notification.style.animation = 'slideOut 0.3s ease';
                setTimeout(() => notification.remove(), 300);
            }, 3000);
        }

        // Load QR URLs on page load
        let machineId = 'VM001';  // Will be updated from status API
        window.addEventListener('load', () => {
            loadQRURLs();
        });
'''

def enhance_telemetry_frontend():
    """Enhance the telemetry frontend HTML with QR management section."""

    frontend_dir = Path(__file__).parent.parent / "monitoni" / "telemetry" / "frontend"
    html_file = frontend_dir / "index.html"

    if not html_file.exists():
        print(f"Error: {html_file} not found!")
        return False

    # Read the HTML file
    with open(html_file, 'r') as f:
        content = f.read()

    # Insert QR Management section before Logs card
    logs_card_pattern = r'(\s+<!-- Logs Card -->)'
    if re.search(logs_card_pattern, content):
        content = re.sub(logs_card_pattern, QR_MANAGEMENT_SECTION + r'\1', content)
        print("✓ Inserted QR Management card")
    else:
        print("! Could not find Logs card marker, skipping section insertion")

    # Insert CSS before closing </style>
    css_pattern = r'(</style>)'
    if re.search(css_pattern, content):
        content = re.sub(css_pattern, QR_MANAGEMENT_CSS + r'\n    \1', content)
        print("✓ Inserted QR Management CSS")
    else:
        print("! Could not find </style> tag, skipping CSS insertion")

    # Insert JavaScript before closing </script> in the main script section
    # Find the last </script> tag (should be the main one)
    script_sections = list(re.finditer(r'</script>', content))
    if script_sections:
        last_script_end = script_sections[-1].start()
        content = content[:last_script_end] + QR_MANAGEMENT_JS + '\n' + content[last_script_end:]
        print("✓ Inserted QR Management JavaScript")
    else:
        print("! Could not find </script> tag, skipping JS insertion")

    # Write the enhanced HTML
    with open(html_file, 'w') as f:
        f.write(content)

    print(f"\n✓ Enhanced telemetry frontend saved to {html_file}")
    return True

if __name__ == "__main__":
    enhance_telemetry_frontend()
